language: r
sudo: false
warnings_are_errors: true

r_binary_packages:
  - XML
  - Rcpp
  - knitr

r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat
  - jimhester/covr
  - jimhester/lintr
  - R-Finance/quantstrat
  - armstrtw/AWS.tools
  - armstrtw/rzmq

after_success:
  - Rscript -e 'library(covr);coveralls()'
  - Rscript -e 'lintr::lint_package()'
