# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('Roanda_timesTwo', PACKAGE = 'Roanda', x)
}

cond_sum_cpp <- function(x, y, z) {
    .Call('Roanda_cond_sum_cpp', PACKAGE = 'Roanda', x, y, z)
}

